### ISSUE TITLE
create test script 

### ISSUE THREAD

**Issue by AurelienRenou** [s2mLab/InverseKinematics#13]
Write tests for testing all the method in the inverse kinematics class

**Comment by AurelienRenou** [comment]
List of function to test:
- [ ] _get_marker_trajectories
- [ ] _get_idx_to_remove
- [ ] _marker_diff
- [ ] _marker_jac
- [ ] solve
- [ ] animate

**Comment by Ipuch** [comment]
to be done in biorbd
